# Generated by Django 2.0.5 on 2018-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='libros',
            field=models.ManyToManyField(blank=True, to='biblioteca.Libro'),
        ),
    ]
